import type { Metadata } from "next";
import "./globals.css";
// import Message from "@/components/Message";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <title>虚拟世界</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      <body>
        {children}
      </body>
    </html>
  );
}
